# Generated by Django 5.0 on 2023-12-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_api_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
